Fix notifications and system tray

diff --git a/.github/workflows/UpdateVersion.yml b/.github/workflows/UpdateVersion.yml
--- a/.github/workflows/UpdateVersion.yml
+++ b/.github/workflows/UpdateVersion.yml
@@ -20,43 +20,13 @@ jobs:
       - name: Validate Tag Name
         run: |
           if [[ ! "${{ github.event.inputs.tagName }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-          echo "Invalid tag name format. Please use the format vX.X.X.X"
-          exit 1
+            echo "Invalid tag name format. Please use the format vX.X.X.X"
+            exit 1
           fi
-
-  build-release-upload:
-    environment: Release
-    runs-on: windows-latest
-    needs: validate-tag
-    strategy:
-      fail-fast: true
-
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v3
-
-      - name: Build and Publish
-        uses: ./.github/templates/ReleaseAndPublish
-
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          path: ./publish/PenumbraModForwarder.zip
-          retention-days: 10
-          name: "artifact"
-
-      - name: Create Release
-        uses: softprops/action-gh-release@v2.0.8
-        with:
-          tag_name: ${{ github.event.inputs.tagName }}
-          files: ./publish/PenumbraModForwarder.zip
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   update-version:
     runs-on: ubuntu-latest
-    needs: build-release-upload
-
+    needs: validate-tag
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
@@ -64,9 +34,10 @@ jobs:
       - name: Update XML and Update URL
         run: |
           version="${{ github.event.inputs.tagName }}"
+          version_stripped="${version#v}"  # Strip the leading 'v'
           xml_file="./update.xml"
           xml=$(cat "$xml_file")
-          xml=$(echo "$xml" | sed "s|<version>.*</version>|<version>${version}</version>|")
+          xml=$(echo "$xml" | sed "s|<version>.*</version>|<version>${version_stripped}</version>|")
           xml=$(echo "$xml" | sed "s|<url>.*</url>|<url>https://github.com/Sebane1/PenumbraModForwarder/releases/download/${version}/PenumbraModForwarder.zip</url>|")
           echo "$xml" > "$xml_file"
         shell: bash
@@ -84,7 +55,6 @@ jobs:
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           commit_message: "[AUTO-COMMIT] Update Version Number"
-          # Make the target branch the version number
           target_branch: ${{ github.event.inputs.tagName }}
 
       - name: Create a PR with the changes
@@ -95,3 +65,4 @@ jobs:
           source_branch: ${{ github.event.inputs.tagName }}
           target_branch: "master"
           get_diff: 'true'
+          label: 'release'
